/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "fmod.hpp"
#include <unistd.h>
#include <string>

using namespace std;

/* Header for class com_derry_derry_voicechange_MainActivity */

#ifndef _Included_com_derry_derry_voicechange_MainActivity
#define _Included_com_derry_derry_voicechange_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_derry_derry_voicechange_MainActivity_MODE_NORMAL
#define com_derry_derry_voicechange_MainActivity_MODE_NORMAL 0L
#undef com_derry_derry_voicechange_MainActivity_MODE_LUOLI
#define com_derry_derry_voicechange_MainActivity_MODE_LUOLI 1L
#undef com_derry_derry_voicechange_MainActivity_MODE_DASHU
#define com_derry_derry_voicechange_MainActivity_MODE_DASHU 2L
#undef com_derry_derry_voicechange_MainActivity_MODE_JINGSONG
#define com_derry_derry_voicechange_MainActivity_MODE_JINGSONG 3L
#undef com_derry_derry_voicechange_MainActivity_MODE_GAOGUAI
#define com_derry_derry_voicechange_MainActivity_MODE_GAOGUAI 4L
#undef com_derry_derry_voicechange_MainActivity_MODE_KONGLING
#define com_derry_derry_voicechange_MainActivity_MODE_KONGLING 5L

/*
 * Class:     com_derry_as_1jni_1projectkt_MainActivity
 * Method:    voiceChangeNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT jstring JNICALL
Java_com_derry_as_1jni_1projectkt_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

extern "C"
JNIEXPORT void JNICALL
Java_com_derry_as_1jni_1projectkt_MainActivity_voiceChangeNative(JNIEnv *env, jobject thiz,
                                                                 jint mode, jstring path);

#ifdef __cplusplus
}
#endif
#endif

